/*
 * Contracts Appraisal
 * This is a an api to provide EVE Online pricing based on public contracts. Results are cached as shown in the Expires header. You can download the swagger.json at https://api.swaggerhub.com/apis/rihanshazih/contracts-appraisal/1.2.0/swagger.json
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eve.nikr.net.client.api;

import eve.nikr.net.client.ApiCallback;
import eve.nikr.net.client.ApiClient;
import eve.nikr.net.client.ApiException;
import eve.nikr.net.client.ApiResponse;
import eve.nikr.net.client.Configuration;
import eve.nikr.net.client.Pair;
import eve.nikr.net.client.ProgressRequestBody;
import eve.nikr.net.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import eve.nikr.net.client.model.Feedback;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FeedbackApi {
    private ApiClient localVarApiClient;

    public FeedbackApi() {
        this(Configuration.getDefaultApiClient());
    }

    public FeedbackApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for giveFeedback
     * @param feedback The feedback to create. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public okhttp3.Call giveFeedbackCall(Feedback feedback, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = feedback;

        // create path and map variables
        String localVarPath = "/feedback";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call giveFeedbackValidateBeforeCall(Feedback feedback, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = giveFeedbackCall(feedback, _callback);
        return localVarCall;

    }

    /**
     * Give feedback on pricing information
     * 
     * @param feedback The feedback to create. (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void giveFeedback(Feedback feedback) throws ApiException {
        giveFeedbackWithHttpInfo(feedback);
    }

    /**
     * Give feedback on pricing information
     * 
     * @param feedback The feedback to create. (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> giveFeedbackWithHttpInfo(Feedback feedback) throws ApiException {
        okhttp3.Call localVarCall = giveFeedbackValidateBeforeCall(feedback, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Give feedback on pricing information (asynchronously)
     * 
     * @param feedback The feedback to create. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public okhttp3.Call giveFeedbackAsync(Feedback feedback, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = giveFeedbackValidateBeforeCall(feedback, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
