/*
 * Contracts Appraisal
 * This is a an api to provide EVE Online pricing based on public contracts. Results are cached as shown in the Expires header. You can download the swagger.json at https://api.swaggerhub.com/apis/rihanshazih/contracts-appraisal/1.2.0/swagger.json
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eve.nikr.net.client.api;

import eve.nikr.net.client.ApiException;
import eve.nikr.net.client.model.Feedback;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FeedbackApi
 */
@Ignore
public class FeedbackApiTest {

    private final FeedbackApi api = new FeedbackApi();

    
    /**
     * Give feedback on pricing information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void giveFeedbackTest() throws ApiException {
        Feedback feedback = null;
        api.giveFeedback(feedback);

        // TODO: test validations
    }
    
}
