/*
 * Contracts Appraisal
 * This is a an api to provide EVE Online pricing based on public contracts. Results are cached as shown in the Expires header. You can download the swagger.json at https://api.swaggerhub.com/apis/rihanshazih/contracts-appraisal/1.2.0/swagger.json
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eve.nikr.net.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Feedback
 */
public class FeedbackTest {
    private final Feedback model = new Feedback();

    /**
     * Model tests for Feedback
     */
    @Test
    public void testFeedback() {
        // TODO: test Feedback
    }

    /**
     * Test the property 'typeId'
     */
    @Test
    public void typeIdTest() {
        // TODO: test typeId
    }

    /**
     * Test the property 'isBpc'
     */
    @Test
    public void isBpcTest() {
        // TODO: test isBpc
    }

    /**
     * Test the property 'oldPricePerUnit'
     */
    @Test
    public void oldPricePerUnitTest() {
        // TODO: test oldPricePerUnit
    }

    /**
     * Test the property 'oldPriceType'
     */
    @Test
    public void oldPriceTypeTest() {
        // TODO: test oldPriceType
    }

    /**
     * Test the property 'suggestedPricePerUnit'
     */
    @Test
    public void suggestedPricePerUnitTest() {
        // TODO: test suggestedPricePerUnit
    }

    /**
     * Test the property 'bpcRuns'
     */
    @Test
    public void bpcRunsTest() {
        // TODO: test bpcRuns
    }

    /**
     * Test the property 'materialEfficiency'
     */
    @Test
    public void materialEfficiencyTest() {
        // TODO: test materialEfficiency
    }

    /**
     * Test the property 'timeEfficiency'
     */
    @Test
    public void timeEfficiencyTest() {
        // TODO: test timeEfficiency
    }

    /**
     * Test the property 'security'
     */
    @Test
    public void securityTest() {
        // TODO: test security
    }

}
