/*
 * Contracts Appraisal
 * This is a an api to provide EVE Online pricing based on public contracts. Results are cached as shown in the Expires header. You can download the swagger.json at https://api.swaggerhub.com/apis/rihanshazih/contracts-appraisal/1.2.0/swagger.json
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eve.nikr.net.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Prices
 */
public class PricesTest {
    private final Prices model = new Prices();

    /**
     * Model tests for Prices
     */
    @Test
    public void testPrices() {
        // TODO: test Prices
    }

    /**
     * Test the property 'typeId'
     */
    @Test
    public void typeIdTest() {
        // TODO: test typeId
    }

    /**
     * Test the property 'typeName'
     */
    @Test
    public void typeNameTest() {
        // TODO: test typeName
    }

    /**
     * Test the property 'median'
     */
    @Test
    public void medianTest() {
        // TODO: test median
    }

    /**
     * Test the property 'average'
     */
    @Test
    public void averageTest() {
        // TODO: test average
    }

    /**
     * Test the property 'minimum'
     */
    @Test
    public void minimumTest() {
        // TODO: test minimum
    }

    /**
     * Test the property 'maximum'
     */
    @Test
    public void maximumTest() {
        // TODO: test maximum
    }

    /**
     * Test the property 'fivePercent'
     */
    @Test
    public void fivePercentTest() {
        // TODO: test fivePercent
    }

    /**
     * Test the property 'contracts'
     */
    @Test
    public void contractsTest() {
        // TODO: test contracts
    }

}
